version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_brocoders_nestjs_todo
    environment:
      POSTGRES_DB: "todo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - brocoders-nestks-todo-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_brocoders_nestjs_todo
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - brocoders-nestks-todo-network

  nestjs_app:
    build:
      context: .
    container_name: nestjs_app
    command: npm run start:dev
    restart:  unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - brocoders-nestks-todo-network
    env_file:
      - .env
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules

volumes:
  postgres_data:
  pgadmin_data:

networks:
  brocoders-nestks-todo-network:
    driver: bridge